### ISSUE TITLE
App Backbone and MySQL DB setup

### ISSUE THREAD

**Issue by ernestmarcinko** [wpdreams/paddle-license-generator#1]
For more detailed specifications please refer to [this document](https://gist.github.com/ernestmarcinko/229462f6255d0e0f27c4ca07fba16d29).

## Server software
Use software/framework of your choice, _tsed_ if you prefer. The backbone has to be capable of:
 - Accepting Secured webhook request from paddle
 - Handling RESTful requests for communication

Don't forget, that the webhooks will obviously only work if **the endpoint is exposed** - so it has to be publicly accessible. Make sure to deal with that so development is smooth.

### Registrering a Paddle Sandbox account
For develoment a Paddle Sandbox account is going to be required. You might be able to register one without being a seller.
 - go to https://sandbox-login.paddle.com/signup
 - select the first option: **Digital Products or SaaS**
 - fill in the details and good to go
 
If the registration is not possible, I will share the business test account via Discord.

## Database
- MySQL 8
- The required databases should be automatically created during init

## TODOS
- [ ] Server base ready for adding new endpoints
- [ ] Configuration file with DB & other credentials like Paddle API key
- [ ] ORM or Native MySQL to interact with the DB
- [ ] Base readme with exact steps of init & deployment scripts howto
