### ISSUE TITLE
REST Endpoint + Webhook after each purchase/subscription and status changes

### ISSUE THREAD

**Issue by ernestmarcinko** [wpdreams/paddle-license-generator#2]
## Description
After each subscription and subscription change this webhook is called by Paddle. It's basically a REST endpoint. After certain conditions it will also call another 3rd party endpoint to send the generated data via POST.

The endpoint path is up to you to decide.

## Setup
 - Log into [paddle sandbox](https://sandbox-vendors.paddle.com/)
 - The hook can be set at **Developer Tools -> Notifications** submenu
 - Set the public URL to the webhook endpoint
 - Select the Events needed (see Trigger Events below)
 - I don't think you need to create a product, but I don't know
 - Go to the [testing page](https://sandbox-vendors.paddle.com/checkout-settings#Overlay) to trigger checkouts and whatnot
 - See their docs [about testing](https://www.paddle.com/help/start/set-up-paddle/how-do-i-test-my-checkout-integration)

You may need an access to my main vendor account for Live testing, if so, lmk via discord. You may need it, as I'm not sure what the sandbox can do.
 
## Trigger Events
This I don't know exactly, it needs to be experimented with, but the least the better, you only want to store as little data as needed and sync it only if neccessary. These are most likely the ones you need:

 - subscription.activated
 - subscription.cancelled
 - subscription.resumed

![image](https://github.com/wpdreams/paddle-license-generator/assets/6159897/f200df9e-7d80-42dc-b5ff-f2a116eac545)

In theory these should be sufficient to generate licenses and to update subscirpion statuses. Please verify if these events also trigger when using "one time" product pricing models and not recurring. I suspect it will work, but make sure.

## Action after trigger

After the data is processed by the endpoint, a WebHook has to be called. The endpoint should be configurable via the config file. The method should be POST.
This is to be used on distributing the license keys via a 3rd party service.

### Call Conditions
 - Only when new subscription or new licenses generated, no trigger on updates
 
### Data to be sent
 - The purchase details
 - Customer details, most importantly email
 - Generated purchase keys (aka licenses) in **uuidv4** format

Example response:

```ts
type Purchase = {
    'id': string, //subscription/purchase id
    'product': Product,
    'customer': Customer,
    'licenses': uuid4[],
}
```

## Data storage & redundancy
 - Aim to store all the required data - start from the response to see what is required, try to minimize
 - Avoid fetching additional data from Paddle unless it's neccessary, store it initially instead - this is to avoid unneccesary issues if paddle servers are offline or have issues
 - Prefer syncing subscription/customer data via the Events instead of fetching Paddle

### What data to store?
- Customer: email, name
- Subscription: start, end, status
- Licenses: generated keys

These should be sufficient to tell if a license is valid and belongs to a certain customer. Extend them on your own if needed.

## TODO
- [ ] Webhook accepting data from Paddle
- [ ] Licenses are generating and stored
- [ ] Subscription data stored
- [ ] Customer data stored
- [ ] Subscription statuses sync on refunds, cancels or renewals
